<?php
// Generated by Zend Framework 2
return array(
    'Album\Controller\AlbumController' => __DIR__ . '/src/Album/Controller/AlbumController.php',
    'Album\Module'                     => __DIR__ . '/Module.php',
);